DJANGO_BLOG/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<username>/profile/', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('quit/', views.quit, name='quit'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

DJANGO_BLOG/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('<int:article_id>/follow/<int:user_id>/', views.follow, name='follow'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/delete/', views.delete, name='delete'),
    path('<int:article_id>/update/', views.update, name='update'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    # path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('jobs/', include('jobs.urls')),
    path('students/', include('students.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGO_BLOG/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

DJANGO_BLOG/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

DJANGO_BLOG/articles/models.py
from django.db import models
from django.conf import settings
# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill, Thumbnail

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # image = ProcessedImageField(                # Win7 OSError issue 로 Win10 이나 Mac 에서만 해주시는걸로..ㅠㅠ
    #     upload_to = 'articles/images',          # 저장 위치(MEDIA_ROOT/articles/images)
    #     processors = [ResizeToFill(200, 300)],  # 처리할 작업 목록
    #     format = 'jpeg',                        # 저장 포맷
    #     options = {'quality':90},               # 추가 옵션
    # )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)

    def __str__(self):
        return f'{self.id}번 글 - {self.title} : {self.content}'

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pk']
        
    def __str__(self):
        return f'<Article({self.article_id}) : Comment({self.id})> - {self.content}'

DJANGO_BLOG/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

class UserCustomCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

DJANGO_BLOG/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from .forms import UserCustomChangeForm, UserCustomCreationForm
from django.contrib.auth import update_session_auth_hash    # 비밀번호 변경시 session_auth_hash 정보를 update
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.user.is_authenticated:   # 인증된 유저가 요청을 보낸 경우, 회원가입 페이지를 보여주지 않고 목록 페이지로 redirect
        return redirect('articles:index')
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCustomCreationForm()
    return render(request, 'accounts/auth_form.html', {'form':form})

def login(request):
    if request.user.is_authenticated:   # 인증된 유저가 요청을 보낸 경우, 로그인 페이지를 보여주지 않고 목록 페이지로 redirect
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout(request):
    if request.method == 'POST':
        auth_logout(request)
    return redirect('articles:index')

def quit(request):
    if request.method == 'POST':
        request.user.delete()
    return redirect('articles:index')

def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    return render(request, 'accounts/auth_form.html', {'form':form})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # 비밀번호 변경 후 기존 로그인된 계정 정보와 일치하지 않아서 자동로그아웃되지 않도록 session_auth_hash 정보를 update 해줌
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/auth_form.html', {'form':form})

@login_required
@require_POST
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    return render(request,'accounts/profile.html', {'person':person})

DJANGO_BLOG/accounts/templates/accounts/auth_form.html
{% extends 'articles/base.html' %}
{% block body %}
{% load bootstrap4 %}
{% if request.resolver_match.url_name == 'signup' %}
<h1 class='text-center'>회원가입</h1>
{% elif request.resolver_match.url_name == 'edit' %}
<h1 class='text-center'>회원정보 수정</h1>
{% else %}
<h1 class='text-center'>비밀번호 변경</h1>
{% endif %}
<form action="" method="POST" style='display:inline'>
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "등록" button_class='btn btn-primary' %}
</form>
<a href="{% url 'articles:index' %}"><button class='btn btn-dark'>취소</button></a>
{% endblock %}

DJANGO_BLOG/accounts/templates/accounts/login.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}
<h1 class='text-center'>로그인</h1>
<form action="" method="POST" style='display:inline'>
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "로그인" button_class='btn btn-primary' %}
</form>
<a href="{% provider_login_url 'kakao' %}"><button class='btn btn-warning'>카카오 로그인</button></a>
<a href="{% url 'articles:index' %}"><button class='btn btn-dark'>취소</button></a>
{% endblock %}

DJANGO_BLOG/accounts/templates/accounts/profile.html
{% extends 'articles/base.html' %}
{% block body %}
<h1 class='text-center'>{{ person.username }}'s Profile</h1>
<hr>
<h3 class='text-center'>{{ person.username }}이 작성한 글</h3>

<div class="row">
    {% for article in person.article_set.all %}
    <div class="col-4">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text">{{ article.like_users.count }} 명이 좋아하는 글</p>
            <p class="card-text">{{ article.comment_set.count }}개의 댓글</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">게시글 보기</a>
        </div>
        </div>
    </div>
    {% endfor %}
</div>

<hr>

<h3 class='text-center'>{{ person.username }}이 작성한 댓글</h3>
<div class='row'>    
    {% for comment in person.comment_set.all %}
    <div class="col-12">
        <div class="card">
        <div class="card-body">
            <blockquote class="blockquote">
                <h3>No.{{ comment.article.id }}: {{ comment.article.title }}</h3>
                <p class="mb-0">{{ comment.content }}</p>
                <footer class="blockquote-footer">{{ comment.created_at|date:"SHORT_DATE_FORMAT" }}</footer>
            </blockquote>
        </div>
        </div>
    </div>
    {% endfor %}   
</div>
<a href="{% url 'articles:index' %}"><button class='btn btn-dark'>메인페이지</button></a>
{% endblock %}